In [2]:
import numpy as np

## Numpy Array

In [3]:
my_list = [1,2,3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
len(np.linspace(0,10,3))

3

In [19]:
#Same as the number of linearly spaced numbers we want.

In [21]:
np.random.rand(5)

array([0.16633866, 0.45500355, 0.85924891, 0.24419063, 0.59950256])

In [22]:
np.random.rand(5,2)

array([[0.80424888, 0.02283186],
       [0.47467953, 0.25149216],
       [0.54122574, 0.36094081],
       [0.52800104, 0.02203032],
       [0.87700695, 0.95886628]])

In [23]:
np.random.randn(5)

array([ 0.32027775,  0.89773385,  0.71626255,  1.46544188, -0.56411235])

In [25]:
np.random.randint(0,5)

4

In [26]:
np.random.randint(0,100,5)

array([51, 59, 43, 96, 80])

In [6]:
np.random.randint(0,100,(5,2))

array([[92, 14],
       [71, 60],
       [20, 82],
       [86, 74],
       [74, 87]])

In [8]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [9]:
arr = np.arange(0,25)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [13]:
arr_1 = np.random.randint(0,101,10)

In [14]:
arr_1

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [15]:
arr_1.max()

99

In [16]:
arr_1.min()

2

In [17]:
arr_1.argmax()

5

In [18]:
#index number

In [19]:
arr_1.argmin()

7

In [20]:
arr_1.dtype

dtype('int32')

In [21]:
 arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.shape

(25,)

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [25]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

## Numpy Indexing and Selection

In [26]:
arr = np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[1]

1

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
arr[:5]

array([0, 1, 2, 3, 4])

In [31]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr[0:5] = 10

In [33]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [34]:
arr = np.arange(0,11)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
slice_of_array = arr[0:5]

In [37]:
slice_of_array

array([0, 1, 2, 3, 4])

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
slice_of_array [:] = 100

In [40]:
slice_of_array

array([100, 100, 100, 100, 100])

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr_copy = arr.copy()

In [50]:
arr_copy[:] = 99

In [51]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [54]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
arr_2d.shape

(3, 3)

In [56]:
arr_2d[0]

array([ 5, 10, 15])

In [57]:
arr_2d[2]

array([35, 40, 45])

In [58]:
arr_2d[0][0]

5

In [59]:
#or

In [60]:
arr_2d[0,0]

5

In [61]:
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [62]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [65]:
bool_arr = arr>4

In [66]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [67]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [68]:
#or

In [69]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

## Numpy Operations

In [71]:
arr = np.arange(0,11)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [75]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [76]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [77]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [78]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [79]:
arr / arr

<ipython-input-79-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
# nan = not a number

In [81]:
1/0

ZeroDivisionError: division by zero

In [82]:
1 / arr

<ipython-input-82-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [83]:
# inf = infinity

In [85]:
# square root

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [86]:
np.log(arr)

<ipython-input-86-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr.sum()

55

In [89]:
arr.max()

10

In [90]:
arr.min()

0

In [91]:
arr.var()

10.0

In [93]:
#Standard diviation

In [94]:
arr.std()

3.1622776601683795

In [96]:
arr_2d = np.arange(0,25).reshape(5,5)

In [97]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [98]:
arr_2d.sum()

300

In [100]:
# axis = 0 means sum across the rows

In [99]:
arr_2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [101]:
# axis = 1 means sum across the columns

In [102]:
arr_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])